name: CI Linter pipeline
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  web:
    name: CI linter for js/ts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: web/yarn.lock

      - name: Install dependencies and lint web app
        working-directory: web
        run: |
          yarn install
          yarn lint  # Adjust linting command as per your project

      - name: Build web app
        working-directory: web
        run: yarn build

  gitness:
    name: CI linter for go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'  # Update to the latest stable version

      - name: Get dependencies
        run: |
          mkdir -p ./web/dist  # Check if this is necessary
          touch ./web/dist/empty.txt  # Check if this is necessary

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54  # Adjust as needed
